const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const DELETE_ALL_ITEM = "DELETE_ALL_ITEM";
const TRACK_CHECKED_STATE = "TRACK_CHECKED_STATE";
const SET_DONE_ALL_ITEMS = "SET_DONE_ALL_ITEMS";
const SET_INPUT_CHANGES = "SET_INPUT_CHANGES";
const SET_EDIT = "SET_EDIT";
const SET_ITEM_TO_EDIT = "SET_ITEM_TO_EDIT";
const SET_EDIT_INPUT_CHANGES = "SET_EDIT_INPUT_CHANGES";
const CHANGE_EDIT_ITEM = "CHANGE_EDIT_ITEM";

export default {
  ADD_ITEM,
  DELETE_ITEM,
  DELETE_ALL_ITEM,
  TRACK_CHECKED_STATE,
  SET_DONE_ALL_ITEMS,
  SET_INPUT_CHANGES,
  SET_EDIT,
  SET_ITEM_TO_EDIT,
  SET_EDIT_INPUT_CHANGES,
  CHANGE_EDIT_ITEM,
};
